
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class menue_manager extends javax.swing.JFrame {
    String s;
    String uname;
    /**
     * Creates new form menue_manager
     */
    public menue_manager() {
        initComponents();
    }
    public menue_manager(String uname,String s) {
        initComponents();
        this.uname=uname;
        this.s=s;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        insert = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        serialno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        type = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setPreferredSize(new java.awt.Dimension(1850, 900));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 80)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("    Menu");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(440, 0, 400, 100);

        jComboBox1.setBackground(new java.awt.Color(102, 255, 255));
        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Biriany", "Rice", "Vegetables", "Curry", "Snacks", "Burger", "Pizza", "Pasta & Chowmin", "Drinks/Beverages" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox1);
        jComboBox1.setBounds(70, 150, 220, 28);

        insert.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        insert.setForeground(new java.awt.Color(102, 0, 0));
        insert.setText("INSERT");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });
        jPanel3.add(insert);
        insert.setBounds(30, 620, 140, 37);

        update.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        update.setForeground(new java.awt.Color(102, 0, 0));
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel3.add(update);
        update.setBounds(260, 620, 130, 37);

        delete.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        delete.setForeground(new java.awt.Color(102, 0, 0));
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel3.add(delete);
        delete.setBounds(510, 620, 120, 37);
        jPanel3.add(serialno);
        serialno.setBounds(710, 160, 110, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 0));
        jLabel3.setText("Serial_NO:");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(590, 170, 110, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 0));
        jLabel4.setText("Name:");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(600, 210, 70, 22);

        jLabel5.setText("jLabel5");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(970, 390, 34, 14);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 0));
        jLabel6.setText("Price:");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(600, 250, 70, 22);
        jPanel3.add(name);
        name.setBounds(710, 210, 110, 30);
        jPanel3.add(price);
        price.setBounds(710, 250, 110, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial_No", "Name", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(70, 190, 452, 402);

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 0));
        jLabel7.setText("Type:");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(600, 290, 100, 22);
        jPanel3.add(type);
        type.setBounds(710, 290, 110, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 0));
        jButton1.setText("HOME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(1140, 0, 120, 37);

        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizza2.png"))); // NOI18N
        jPanel3.add(jLabel1);
        jLabel1.setBounds(0, 0, 2140, 770);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1824, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String option=jComboBox1.getSelectedItem().toString();
        // TODO add your handling code here:
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","manager","manager");
            PreparedStatement ps=conn.prepareStatement("select SERIAL_NO,NAME,PRICE FROM ITEM where ITEM_TYPES=?");
            //Statement st=conn.createStatement();
            ps.setString(1, option);
            ResultSet rs=ps.executeQuery();

            while(jTable1.getRowCount()>0)
            {
                ((DefaultTableModel)jTable1.getModel()).removeRow(0);

            }
            int col=rs.getMetaData().getColumnCount();
            while(rs.next())
            {  //  option=rs.getString("ITEM_TYPES");
                Object [] rows=new Object[col];
                for(int i=1;i<=col;i++)
                {
                    rows[i-1]=rs.getObject(i);
                }
                ((DefaultTableModel)jTable1.getModel()).insertRow(rs.getRow()-1,rows);
            }
            rs.close();
            ps.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        // TODO add your handling code here:
        try{
             Class.forName("oracle.jdbc.driver.OracleDriver");
             Connection conn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","manager","manager");
        
        PreparedStatement ps=conn.prepareStatement("insert into Item(Serial_No,Name,Price,Item_Types) values(?,?,?,?)");
        
        
       String s1=serialno.getText();
       String s2=name.getText();
       String s3=price.getText();
       String s4=type.getText();
        ps.setString(1,s1);
        ps.setString(2,s2);
        ps.setString(3,s3);
        ps.setString(4,s4);
      
        ps.executeUpdate();
         String option=jComboBox1.getSelectedItem().toString();
           PreparedStatement ps1=conn.prepareStatement("select SERIAL_NO,NAME,PRICE FROM ITEM where ITEM_TYPES='"+option+"'");
            //Statement st=conn.createStatement();
           // ps1.setString(1, option);
            ResultSet rs=ps1.executeQuery();

            while(jTable1.getRowCount()>0)
            {
                ((DefaultTableModel)jTable1.getModel()).removeRow(0);

            }
            int col=rs.getMetaData().getColumnCount();
            while(rs.next())
            {  //  option=rs.getString("ITEM_TYPES");
                Object [] rows=new Object[col];
                for(int i=1;i<=col;i++)
                {
                    rows[i-1]=rs.getObject(i);
                }
                ((DefaultTableModel)jTable1.getModel()).insertRow(rs.getRow()-1,rows);
            }
        conn.close();
        ps.close();
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_insertActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
          try{
             Class.forName("oracle.jdbc.driver.OracleDriver");
             Connection conn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","manager","manager");
             int row=jTable1.getSelectedRow();
             String value=(jTable1.getModel().getValueAt(row,0).toString());
             PreparedStatement ps=conn.prepareStatement("update Item set Serial_No=?,Name=?,Price=?,Item_Types=? where Serial_No="+value);
             String s1=serialno.getText();
       String s2=name.getText();
       String s3=price.getText();
       String s4=type.getText();
        ps.setString(1,s1);
        ps.setString(2,s2);
        ps.setString(3,s3);
        ps.setString(4,s4);
        ps.executeUpdate();
         String option=jComboBox1.getSelectedItem().toString();
        Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery("select Serial_No,Name,price from Item where Item_types='"+option+"' ");
            
            while(jTable1.getRowCount()>0)
            {
                ((DefaultTableModel)jTable1.getModel()).removeRow(0);
                
            }
            int col=rs.getMetaData().getColumnCount();
            while(rs.next())
            {
                Object [] rows=new Object[col];
                for(int i=1;i<=col;i++)
                {
                    rows[i-1]=rs.getObject(i);
                }
                ((DefaultTableModel)jTable1.getModel()).insertRow(rs.getRow()-1,rows);
            }
        conn.close();
        ps.close();
          } 
            catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
         try{
             Class.forName("oracle.jdbc.driver.OracleDriver");
             Connection conn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","manager","manager");
             int row=jTable1.getSelectedRow();
             String value=(jTable1.getModel().getValueAt(row,0).toString());
             PreparedStatement ps=conn.prepareStatement("Delete from item where Serial_No="+value);
             ps.executeUpdate();
              String option=jComboBox1.getSelectedItem().toString();
        Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery("select Serial_No,Name,price from Item where Item_types='"+option+"' ");
            
            while(jTable1.getRowCount()>0)
            {
                ((DefaultTableModel)jTable1.getModel()).removeRow(0);
                
            }
            int col=rs.getMetaData().getColumnCount();
            while(rs.next())
            {
                Object [] rows=new Object[col];
                for(int i=1;i<=col;i++)
                {
                    rows[i-1]=rs.getObject(i);
                }
                ((DefaultTableModel)jTable1.getModel()).insertRow(rs.getRow()-1,rows);
            }
        conn.close();
        ps.close();
             
         }
         catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        } 
    }//GEN-LAST:event_deleteActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         int i=jTable1.getSelectedRow();
        TableModel model=jTable1.getModel();
        serialno.setText(model.getValueAt(i,0).toString());
        name.setText(model.getValueAt(i,1).toString());
        price.setText(model.getValueAt(i,2).toString());
        type.setText(jComboBox1.getSelectedItem().toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
     Manager_homepage mh=new Manager_homepage(uname,s);
        mh.setVisible(true);
        menue_manager cp=new menue_manager(uname,s);
        cp.setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menue_manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menue_manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menue_manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menue_manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menue_manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete;
    private javax.swing.JButton insert;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField price;
    private javax.swing.JTextField serialno;
    private javax.swing.JTextField type;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

   
}
